version: '3.7'
services:
  postgres:
    image: postgres:14.10
    container_name: gsm-postgres-db
    environment:
      POSTGRES_DB: gsm
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: