CREATE TABLE IF NOT EXISTS USER_
(
    ID_          UUID PRIMARY KEY NOT NULL,
    USER_NAME_   VARCHAR(36)      NOT NULL,
    PASSWORD_    VARCHAR(256)     NOT NULL
    );

CREATE TABLE IF NOT EXISTS TOKEN_
(
    ID_             UUID             PRIMARY KEY NOT NULL,
    ISSUED_AT_      TIMESTAMP        NOT NULL,
    USER_ID_        UUID             NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMER_
(
    ID_         UUID PRIMARY KEY NOT NULL,
    NAME_       VARCHAR(256)     NOT NULL,
    SURNAME_    VARCHAR(256)     NOT NULL,
    BIRTHDATE_  TIMESTAMP        NOT NULL,
    GSM_NUMBER_ VARCHAR(32)      NOT NULL,
    BALANCE_    NUMERIC(12, 2)      NOT NULL,
    USER_ID_    UUID REFERENCES  USER_(ID_)
    );

DO $$
BEGIN
BEGIN
CREATE TYPE TRANSACTION_TYPE AS ENUM ('PURCHASE', 'TOP_UP', 'REFUND');
CREATE CAST (VARCHAR AS TRANSACTION_TYPE) WITH INOUT AS IMPLICIT;
EXCEPTION
            WHEN DUPLICATE_OBJECT THEN
            -- DO NOTHING, TYPE ALREADY EXISTS
END;
END $$;

CREATE TABLE IF NOT EXISTS TRANSACTION_
(
    ID_                     UUID PRIMARY KEY NOT NULL,
    AMOUNT_                 NUMERIC(5, 2)     NOT NULL,
    DATE_                   TIMESTAMP         NOT NULL,
    TYPE_                   TRANSACTION_TYPE NOT NULL,
    CUSTOMER_ID_            UUID REFERENCES  CUSTOMER_(ID_),
    ORIGINAL_TRANSACTION_ID_ UUID,
    FOREIGN KEY (ORIGINAL_TRANSACTION_ID_) REFERENCES TRANSACTION_(ID_)
    );


CREATE UNIQUE INDEX IF NOT EXISTS GSM_NUMBER_
    ON CUSTOMER_ (GSM_NUMBER_);